on:
  schedule:
  - cron: "0 7 * * 0"
  push:
    branches:
      - master

name: send-daily-verbs

jobs:
  render:
    name: send-daily-verbs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v1
      - name: Install telegram.bot and purrr
        run: |
          install.packages("telegram.bot")
          install.packages("purrr")
        shell: Rscript {0}
      - name: Create and populate .Renviron file
        run: |
          echo R_TELEGRAM_BOT_verbs="$TOKEN" >> ~/.Renviron
          shell: bash
      - name: Execute Bot Script
        run: |
          Rscript R/send-message.R
