on:
  schedule:
  - cron: "0 10 * * 0"

name: send-daily-verbs

jobs:
  render:
    name: send-daily-verbs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies ubuntu
        run: |
          sudo apt-get install libcurl4-openssl-dev
      - name: Create and populate .Renviron file
        env:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          echo R_TELEGRAM_BOT_verbs="$TOKEN" >> ~/.Renviron
        shell: bash
      - name: Install telegram.bot and purrr
        run: |
          install.packages("remotes")
          remotes::install_cran("telegram.bot")
          remotes::install_cran("purrr")
        shell: Rscript {0}
      - name: Execute bot script
        run: |
          Rscript R/send-message.R
